/**
 * Hand-written shapes for opencode server fields the checked-in SDK types omit.
 *
 * `packages/sdk/js/src/gen/*` is generated but NOT regenerated by the SDK build script, so it has
 * drifted from the server. Every cast in this package routes through here, with the citation that
 * justifies it, so a codegen refresh has exactly one place to break. `test/drift/` re-reads the
 * real opencode sources and fails when one of these becomes wrong — or unnecessary.
 *
 * All citations are against opencode v1.18.20.
 */

import type { Ruleset } from "./bridge/permission.js"

/**
 * Body accepted by `POST /session`.
 *
 * Source of truth: `packages/opencode/src/session/session.ts:260-271` (`Session.CreateInput`).
 * The SDK's `SessionCreateData["body"]` (`types.gen.ts:2082-2092`) declares only
 * `{parentID?, title?}` — `agent`, `model`, `permission`, `metadata` and `workspaceID` all need
 * this cast even though the server accepts them.
 *
 * NOTE the model shape here is `{id, providerID, variant?}` — DIFFERENT from the prompt body's
 * `{providerID, modelID}` (session.ts:216-220 vs prompt.ts:1494-1497).
 */
export type CreateSessionBody = {
  parentID?: string
  title?: string
  agent?: string
  model?: { id: string; providerID: string; variant?: string }
  metadata?: Record<string, unknown>
  permission?: Ruleset
  workspaceID?: string
}

/** A json_schema output format. `retryCount` is decoded with a default of 2 and then never read. */
export type OutputFormat = { type: "text" } | { type: "json_schema"; schema: Record<string, unknown> }

/**
 * Body accepted by `POST /session/:id/message`.
 *
 * Source of truth: `packages/opencode/src/session/prompt.ts:1494-1521` (`SessionPrompt.PromptInput`,
 * minus `sessionID`, which travels in the path). The SDK's `SessionPromptData["body"]`
 * (`types.gen.ts:2588-2613`) omits `format` and `variant`.
 *
 * `variant` is a SIBLING of `model`, not a field inside it — and it is honoured unconditionally
 * (`prompt.ts:654` reads `input.variant ?? ...`), unlike an agent-configured variant which only
 * applies when the resolved model equals the agent's configured model.
 *
 * `tools` is deliberately absent from this type: passing it PERSISTS a wholesale replacement of
 * the session's permission ruleset (`prompt.ts:1060-1066`), silently wiping the child's denies for
 * every later turn. Tool restrictions belong in the create-time ruleset instead.
 */
export type PromptBody = {
  parts: Array<{ type: "text"; text: string; synthetic?: boolean }>
  messageID?: string
  model?: { providerID: string; modelID: string }
  agent?: string
  variant?: string
  format?: OutputFormat
  system?: string
  noReply?: boolean
}

/** Error names that can appear on `info.error`. Not all are in the SDK's narrower union. */
export type AssistantErrorName =
  | "MessageAbortedError"
  | "StructuredOutputError"
  | "ContextOverflowError"
  | "ContentFilterError"
  | "MessageOutputLengthError"
  | "ProviderAuthError"
  | "APIError"
  | "UnknownError"

/**
 * The assistant message returned by a prompt.
 *
 * Source of truth: `packages/schema/src/v1/session.ts:453-491`. The SDK's `AssistantMessage`
 * (`types.gen.ts:112-141`) omits `structured`, `variant` and `agent`, and its `error` union is
 * missing StructuredOutputError, ContextOverflowError and ContentFilterError.
 *
 * `structured` is the field that carries schema-forced output — NOT `structured_output`, which is
 * what the published docs claim.
 */
export type AssistantInfo = {
  id: string
  sessionID: string
  role: "assistant"
  modelID: string
  providerID: string
  agent?: string
  variant?: string
  structured?: unknown
  cost: number
  tokens: {
    input: number
    output: number
    reasoning: number
    total?: number
    cache: { read: number; write: number }
  }
  error?: { name: AssistantErrorName; data?: Record<string, unknown> }
  time: { created: number; completed?: number }
}

/** A part on the returned message. Only the fields this plugin reads are modelled. */
export type MessagePart =
  | { type: "text"; text: string }
  | { type: "tool"; tool: string; state?: { status?: string } }
  | { type: "step-start" | "step-finish" | "reasoning" | string }

/**
 * The prompt response envelope.
 *
 * IMPORTANT: this carries only the FINAL assistant message of the turn, not the whole turn.
 * Verified empirically in M0 — a turn whose history showed `grep` then `read` then an answer came
 * back here as one step with no research tool parts. So `agent()` extracting its result from this
 * envelope is correct, but part counts here are NOT evidence of what the agent did.
 */
export type PromptResponse = {
  info: AssistantInfo
  parts: MessagePart[]
}

/** Minimal session row, covering the fields the recursion guard and cleanup need. */
export type SessionInfo = {
  id: string
  parentID?: string
  directory?: string
  title?: string
  metadata?: Record<string, unknown>
}

/**
 * The subset of the opencode SDK client this plugin uses.
 *
 * Declared structurally rather than imported so the plugin compiles against the real client while
 * still seeing the undeclared fields. Every method here is called with the injected
 * `PluginInput.client` — never a self-built client, which would re-arm the 5-minute fetch timeout
 * and, under `opencode run`, target a fabricated `http://localhost:4096` that points at nothing.
 */
export type OpencodeClient = {
  /**
   * Used once per run to read each model's real reasoning-variant set.
   *
   * Optional: effort resolution degrades to "no variants known" when it is absent or fails, which
   * reports every effort request as unhonoured rather than sending a variant that may not exist.
   */
  config?: {
    providers: () => Promise<{ data?: { providers?: Array<{ id?: string; models?: Record<string, { variants?: Record<string, unknown> } | undefined> }> }; error?: unknown }>
    get?: () => Promise<{ data?: { model?: string }; error?: unknown }>
  }
  session: {
    create: (options: { body?: CreateSessionBody; query?: { directory?: string } }) => Promise<{
      data?: SessionInfo
      error?: unknown
    }>
    get: (options: { path: { id: string } }) => Promise<{ data?: SessionInfo; error?: unknown }>
    delete: (options: { path: { id: string } }) => Promise<{ data?: unknown; error?: unknown }>
    abort: (options: { path: { id: string } }) => Promise<{ data?: unknown; error?: unknown }>
    prompt: (options: { path: { id: string }; body: PromptBody }) => Promise<{
      data?: PromptResponse
      error?: unknown
    }>
  }
}

/**
 * Adapts the real SDK client to {@link OpencodeClient}.
 *
 * The one place the undeclared-field casts are concentrated. Isolated in a function so the drift
 * test can point at it, and so a future SDK regen breaks here rather than across the codebase.
 */
export function asClient(client: unknown): OpencodeClient {
  return client as OpencodeClient
}
